version: "3.8"

services:
  psql-db:
    image: vanthanhdocker/ecommerce_ehb:db_v1.6
    container_name: psql-db_v6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ecommerce
    ports:
      - '5433:5432'

  app:
    image: vanthanhdocker/ecommerce_ehb:v1.6
    container_name: ecommerce_app_v6
    ports:
      - '9991:9991'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db_v6:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - psql-db
