const SERVER_ALIAS = `${process.env.NEXT_PUBLIC_SERVER_API_URL}/${process.env.NEXT_PUBLIC_SERVER_API_PREFIX}/${process.env.NEXT_PUBLIC_SERVER_API_VERSION}`;
const LOG_LEVEL = `${process.env.NEXT_PUBLIC_LOG_LEVEL}`;

export { SERVER_ALIAS, LOG_LEVEL };
